export const GET_SMURFS_SUCCESS = 'GET_SMURFS_SUCCESS';
export const GET_SMURFS_FAILURE = 'GET_SMURFS_FAILURE';
export const TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM';
export const SET_EDITING_SMURF = 'SET_EDITING_SMURF';