export const GET_SMURFS_SUCCESS = 'GET_SMURFS_SUCCESS';
export const GET_SMURFS_FAILURE = 'GET_SMURFS_FAILURE';
export const TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM';
export const SET_EDITING_SMURF = 'SET_EDITING_SMURF';
export const SET_SMURF_CANDIDATE = 'SET_SMURF_CANDIDATE';
export const RESET_SMURF_CANDIDATE = 'RESET_SMURF_CANDIDATE';
export const ADD_SMURF_SUCCESS = 'ADD_SMURF_SUCCESS';
export const ADD_SMURF_FAILURE = 'ADD_SMURF_FAILURE';
